#!/bin/bash -l
#PBS -N jd_cado_nfs
#PBS -l nodes=1:ppn=10
#PBS -l walltime=10:00:00
#PBS -q batch
#PBS -m abe
#PBS -m rudiejd@miamioh.edu
#Comment - batch job setup complete
cd mrbayes
module load mrbayes
mb batch. nex
